[versions]
kotlin = "2.3.21"
clikt = "5.1.0"
kotlinInject = "0.9.0"
ksp = "2.3.4"
compose = "1.9.3"
kermit = "2.1.0"
lwjgl = "3.4.2"
lwjgl3Awt = "0.2.4"
jinput = "2.0.10"
kotlinxBrowser = "0.3"

[libraries]
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }

kotlinInjectCompiler = { module = "me.tatarka.inject:kotlin-inject-compiler-ksp", version.ref = "kotlinInject" }
kotlinInjectRuntime = { module = "me.tatarka.inject:kotlin-inject-runtime", version.ref = "kotlinInject" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

lwjgl = { module = "org.lwjgl:lwjgl", version.ref = "lwjgl" }
lwjglJawt = { module = "org.lwjgl:lwjgl-jawt", version.ref = "lwjgl" }
lwjglOpenGl = { module = "org.lwjgl:lwjgl-opengl", version.ref = "lwjgl" }
lwjglOpenal = { module = "org.lwjgl:lwjgl-openal", version.ref = "lwjgl" }
jinput = { module = "net.java.jinput:jinput", version.ref = "jinput" }
kotlinxBrowser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlinxBrowser" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
