[versions]
kotlin = "2.3.21"
clikt = "5.1.0"
kotlinInject = "0.9.0"
ksp = "2.3.4"
compose = "1.9.3"
kermit = "2.1.0"
lwjgl = "3.4.2"
swt = "3.134.0"
jna = "5.18.1"

[libraries]
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }

kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

kotlinInjectCompiler = { module = "me.tatarka.inject:kotlin-inject-compiler-ksp", version.ref = "kotlinInject" }
kotlinInjectRuntime = { module = "me.tatarka.inject:kotlin-inject-runtime", version.ref = "kotlinInject" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

lwjgl = { module = "org.lwjgl:lwjgl", version.ref = "lwjgl" }
lwjglGlfw = { module = "org.lwjgl:lwjgl-glfw", version.ref = "lwjgl" }
lwjglOpenal = { module = "org.lwjgl:lwjgl-openal", version.ref = "lwjgl" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
swtMacosAarch64 = { module = "org.eclipse.platform:org.eclipse.swt.cocoa.macosx.aarch64", version.ref = "swt" }
swtMacosX64 = { module = "org.eclipse.platform:org.eclipse.swt.cocoa.macosx.x86_64", version.ref = "swt" }
swtLinuxAarch64 = { module = "org.eclipse.platform:org.eclipse.swt.gtk.linux.aarch64", version.ref = "swt" }
swtLinuxX64 = { module = "org.eclipse.platform:org.eclipse.swt.gtk.linux.x86_64", version.ref = "swt" }
swtWindowsAarch64 = { module = "org.eclipse.platform:org.eclipse.swt.win32.win32.aarch64", version.ref = "swt" }
swtWindowsX64 = { module = "org.eclipse.platform:org.eclipse.swt.win32.win32.x86_64", version.ref = "swt" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
